name: Pull Request Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"


jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install and tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          make test
